# # docker-compose.yml
# services:
#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend

#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "5000:5000"

services:
  backend:
    image: suman0509/drdo-backend:latest
    ports:
      - "5000:5000"
  frontend:
    image: suman0509/drdo-frontend:latest
    ports:
      - "3000:3000"
